name: pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run build-storybook
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: 'storybook-static'
